### ISSUE TITLE
How can I get access_token after login

### ISSUE THREAD

**Issue by RezaRahmati** [heresy/angular2-social-login#1]
Hey, 

Great library, but how can I get access_token after login , to call other apis (for example getting friend list)

**Comment by kurapatijayaram** [comment]
Hi @RezaRahmati , thank you so much for using this. My intention is to develop a simple client side authentication module which doesn't need any backend server and for that only few information is enough like name,email,image_url.
But many users were asking like you , let me think and decide whether I can include that or not ?
