### ISSUE TITLE
google access_token instead of id_token

### ISSUE THREAD

**Issue by m-o-t-u** [heresy/angular2-social-login#10]
Hello

Your project is really nice, but I have a problem with the response-object for google.
Is it possible to return the access_token instead of the id_token? Or can you provide an additional property "access_token" for _fetchGoogleUserDetails()

Example:
```typescript
private _fetchGoogleUserDetails(){
        let currentUser = this.gauth.currentUser.get();
        let profile = currentUser.getBasicProfile();
        let idToken = currentUser.getAuthResponse().id_token;
        let accessToken = currentUser.getAuthResponse().access_token;
        return {
            token: idToken,
            access_token: accessToken,
            uid: profile.getId(),
            name: profile.getName(),
            email: profile.getEmail(),
            image: profile.getImageUrl(),
            provider: "google"
        };
    }
```
Best regards
Martin

**Comment by kevinrfx8** [comment]
Hi 
Also if the linkedin login method could fetch the accessToken would be great!
Greetings!

**Comment by kurapatijayaram** [comment]
Hi @m-o-t-u, let me think about adding accessToken for google, most probably I will try to update by this week.

Thank you.

**Comment by kurapatijayaram** [comment]
Hi @kevinrfx8, as of my knowledge LinkedIn is not providing accessToken through SDK.

Thank You.

**Comment by kurapatijayaram** [comment]
I am closing this because this is not an issue.
