### ISSUE TITLE
Support for redirect mode for Google Auth API

### ISSUE THREAD

**Issue by craigaps** [heresy/angular2-social-login#14]
Hi

I would update the provider configuration to allow for Google sign in options.  For example:

`let providers = { "google": { "clientId": "1234abcd", "ux_mode":"redirect" } }`

Then in angular2-social-login.modules.ts you can assign the attribute, similar to how the clientId is assigned, for example:

`gapi.load('auth2', function() {
                        gapi.auth2.init({
                        client_id: info["clientId"],
                        scope: 'email',
                        ux_mode: info["ux_mode"]
                        })
                    })
`

In addition the attribute needs to be assigned to the auth.service.ts, as follows:

`this.gauth.signIn({'ux_mode': 'redirect'}).then(() => {
                                            localStorage.setItem('_login_provider', 'google');
                                            observer.next(this._fetchGoogleUserDetails());
                                            observer.complete();
                                        });`

Might have to check if the attribute exists in the JSON first before assignment, otherwise default it to ux_mode: **popup**

Ideally, be great if you could add all the [SigninOptions](https://developers.google.com/identity/sign-in/web/reference#gapiauth2signinoptions) where they make sense.

Thanks

**Comment by kurapatijayaram** [comment]
Hi @craigaps, right now we are not at all interested in this feature. I am closing this because this is not an issue.

Thank you.
