### ISSUE TITLE
IN.USER in un defined

### ISSUE THREAD

**Issue by ozrite** [heresy/angular2-social-login#15]
Please check why this error is coming up.Facbook and  google authentication is working properly, however, when "signIn('linkedin')" function is called, Error shows up OF IN.USER undefined. Please check andreport back as I am currently working on a project which needs integration of all three API's for social login. Help will be much appreciated.  For information, I am using angular-CLI.

![linkden error](https://cloud.githubusercontent.com/assets/985842/25891221/ab3553d8-3589-11e7-844a-180b1e53b162.png)

EXCEPTION: Error in ./LoginComponent class LoginComponent - inline template:44:29 caused by: IN.User is undefined  vendor.bundle.js:62276:9
ORIGINAL EXCEPTION: IN.User is undefined

**Comment by ozrite** [comment]
solved. It was due to incomplete settings at the linkedIn side.

**Comment by Celebes** [comment]
Nice that you've solved it, but it would be even nicer if you provided how. Which settings on the linkedIn side were incomplete?

Edit:
You have to go to settings -> JavaScript, and add your app domains. I added "http://www.mydomain.com" and "http://localhost" for testing.
