### ISSUE TITLE
Return of data

### ISSUE THREAD

**Issue by YuriFontella** [heresy/angular2-social-login#17]
I have this scenario:

app component
```
  logged = false;
  user: any;

  login(provider) {
    this.auth.login(provider).subscribe((data) => {
      this.logged = true;
      this.user = data;

      console.log(data);
    });
  }
```
app html
```
  <button *ngIf="!logged" (click)="login('facebook')">Login</button>

  <ul *ngIf="logged">
    <li>{{user.name}}</li>
  </ul>
```

Conclusion:

After logging in, the button does not disappear and the data is not loaded ... but if I click the button again, the data is loaded and the button disappears (the login screen does not appear again).

It would be very strange for the user to have to double-click the login button, would anyone have any idea what might be happening?

**Edit:**

Only the data is not loaded, when I log in for the first time ... after closing the login popup window, it happens. But if I'm already logged in to facebook, and I try to log in, the popup is not requested and the user data is loaded.

**Comment by qasdf123** [comment]
Did you manage to solve this issue? I'm facing the same issue as well.

**Comment by YuriFontella** [comment]
I changed this plugin through a service... 

https://gist.github.com/YuriFontella/2c993aefebebfdaa1e7c84b649e0d257

and facebook: ngx-facebook
