### ISSUE TITLE
Revision

### ISSUE THREAD

**Issue by YuriFontella** [heresy/angular2-social-login#19]
in auth.service logout switch/case

```
gSignout.src = "https://accounts.google.com/Logout";
gSignout.type = "text/html";
```

The error in the console would disappear after logout.

---

Logout on facebook works best this way

```
FB.logout();
localStorage.removeItem('_login_provider');
observer.next(true);
observer.complete();
```

**Comment by kurapatijayaram** [comment]
thanks @YuriFontella , changes done.

**Comment by YuriFontella** [comment]
If it can verify the case facebook in login function ... there is an initial if response.status === "connected" and in the else statement it also does this verification.

**Comment by kurapatijayaram** [comment]
I didn't get you? what is the issue?

**Comment by YuriFontella** [comment]
No problem.
I just found it unnecessary.
