### ISSUE TITLE
Logout not working for Google

### ISSUE THREAD

**Issue by qasdf123** [heresy/angular2-social-login#27]
Hi, 
  Once i  login using google i cannot logout, even though i've added the logout codes. When i click logout and login again the previous logged in user's data is displayed. And there are no errors. Did i missed something?

**Comment by mandeepbhourji** [comment]
Even I am also facing the same issue. Unable to logout for the google account. No errors in the console.
Did you find the solution for this?

**Comment by qasdf123** [comment]
It's nothing to do with this plugin. My site is locally hosted and read somewhere that google doesn't have logout services for locally hosted sites.
