### ISSUE TITLE
Check if Facebook is logged in before calling FB.Login()

### ISSUE THREAD

**Issue by MaZZly** [heresy/angular2-social-login#5]
I get an error when signing in with Facebook due to already being authenticated with the app..

Following solution from old project of mine works to check status before calling Login:
```javascript
FB.getLoginStatus(function (response) {
    if (response.status === 'connected') {
        console.log(response); // contains user data, name, profile etc etc
    } else {
        FB.login(function (response) {
            if (response.status === 'connected') {
                console.log(response); // contains user data, name, profile etc etc
            }
        });
    }
});
```

Also please add accessToken to returned object when using fb login https://github.com/heresy/angular2-social-login/issues/4

**Comment by kurapatijayaram** [comment]
Hi @MaZZly , I am aware of this bug and I am ready with the fix but I will push the code in this week with some changes along with accessTokens if possible.

Thank you.

**Comment by kurapatijayaram** [comment]
Check v2.1.0
