### ISSUE TITLE
facebook api version 

### ISSUE THREAD

**Issue by maku** [heresy/angular2-social-login#8]
From the code I saw that Facebook API v2.4 is used.

Is there a reason why a rather old version is used and are there plans to update to a more recent version?

**Comment by kurapatijayaram** [comment]
@maku We didn't mention any FB API version.

**Comment by maku** [comment]
@kurapatijayaram Oh sorry, the api version is in the provider def of the example project (https://github.com/heresy/angular2-social-login-example/blob/master/app/main.module.ts) -> "apiVersion": "v2.4"

This confused me... BTW, is it necessary to define this for facebook?

**Comment by kurapatijayaram** [comment]
ya you should specify version number for FB
